[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

filterwarnings =
    ignore:.*PydanticDeprecatedSince20.*
    ignore:.*class-based `config` is deprecated.*
    ignore:.*shapely\.geos.*:DeprecationWarning
    ignore:.*PROJ.*:UserWarning
    ignore:.*PROJ.*:Warning
    ignore:.*rasterio.*:UserWarning
    ignore:.*rasterio.*:DeprecationWarning
    ignore:.*planetary_computer.*:UserWarning
    ignore:.*planetary_computer.*:DeprecationWarning
    ignore:.*planetary_computer.*:Warning
